name: Generate ASCII ARTWORK

on: push

jobs:
    build-JOB-1:
        runs-on: ubuntu-latest
        steps:
        - name: Update apt cache
          run: sudo apt-get update

        - name: Install cowsay
          run: sudo apt-get install cowsay -y

        - name: Execute cowsay Program
          run: cowsay -f dragon "Run for cover , i am a Dragon.....RAWR" >> dragon.txt

        - name: Checkout repository
          uses: actions/checkout@v4

        - name: upload the dragon text file
          uses: actions/upload-artifact@v4
          with:
            name: dragon-txt-file
            path: dragon.txt
        
    test-JOB-2:
        runs-on: ubuntu-latest
        needs: build-JOB-1
        steps:
        - name: download the dragon text file
          uses: actions/download-artifact@v4
          with:
            name: dragon-txt-file
             

        - name: test file exists
          run: grep -i "dragon" dragon.txt
    
    deploy-JOB-3:
        needs: test-JOB-2
        runs-on: ubuntu-latest
        steps:
        - name: download the dragon text file
          uses: actions/download-artifact@v4
          with:
            name: dragon-txt-file

        - name: Read File
          run: cat dragon.txt

        - name: Deploy
          run: echo Deploying ... .. .

    
    
        
        # - name: Test File Exists
        #   run: grep -i "dragon" dragon.txt
        
        # - name: Read files
        #   run: cat dragon.txt
          
        # - name: List Repo Files
        #   run: ls -ltra
        
        
        # - name: list files
        #   run: ls
        
        # - name: Read file
        #   run: cat readme.md

