name: Generate ASCII ARTWORK

on: push

jobs:
    build-JOB-1:
        runs-on: ubuntu-latest
        steps:
        - name: Install cowsay
          run: sudo apt-get install cowsay -y

        - name: Execute cowsay Program
          run: cowsay -f dragon "Run for cover , i am a Dragon.....RAWR" >> dragon.txt

        - name: Sleep for 30 seconds
          run: sleep 30
        
    test-JOB-2:
        runs-on: ubuntu-latest
        steps:
        - name: sleep for 10 seconds
          run: sleep 10

        - name: test file exists
          run: grep -i "dragon" dragon.txt
    
    deploy-JOB-3:
        runs-on: ubuntu-latest
        steps:
        - name: Read File
          run: cat dragon.txt

        - name: Deploy
          run: echo Deploying ... .. .

    
    
        
        # - name: Test File Exists
        #   run: grep -i "dragon" dragon.txt
        
        # - name: Read files
        #   run: cat dragon.txt
          
        # - name: List Repo Files
        #   run: ls -ltra
        
        
        # - name: list files
        #   run: ls
        
        # - name: Read file
        #   run: cat readme.md

